import os
import pandas as pd
import re

# Set the working directory to the script's location
script_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(script_dir)

def load_excel(file_path):
    """
    Loads the Excel file into a pandas DataFrame.
    
    Args:
        file_path (str): The path to the Excel file.

    Returns:
        pd.DataFrame: DataFrame containing the contents of the Excel file.
    """
    try:
        df = pd.read_excel(file_path)
        return df
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return None

def find_duplicates(df):
    """
    Finds and prints duplicate entries in the DataFrame based on 'race_id' and 'horse_name'.
    
    Args:
        df (pd.DataFrame): DataFrame containing race data.
    """
    # Identify duplicates based on race_id and horse_name
    duplicates = df[df.duplicated(subset=['race_id', 'horse_name'], keep=False)]
    
    if not duplicates.empty:
        # If duplicates exist, print the file number, race ID, and horse name for the duplicates
        print("Duplicate entries found:")
        duplicate_pairs = duplicates[['file_number', 'race_id', 'horse_name']]
        print(duplicate_pairs)
    else:
        print("No duplicates found.")

def extract_date_from_text(text_block):
    """
    Extracts the date from the first line of the given text block.
    
    Args:
        text_block (str): Text block where the first line contains the date.

    Returns:
        str: Formatted date in 'Month Day, Year' format if successful, otherwise None.
    """
    lines = text_block.strip().splitlines()
    date_line = lines[0].strip()  # First line is assumed to be the date
    date_pattern = r'(\w+), (\w+) (\d{1,2}) (\d{4})'
    
    # Match the date pattern
    match = re.match(date_pattern, date_line)
    if match:
        day_name, month, day, year = match.groups()
        return f'{month} {day}, {year}'
    else:
        print("Invalid date format in the text block.")
        return None

def check_tracks_in_excel(df, text_block):
    """
    Checks if each track name from the text block is present in the DataFrame for the corresponding date.
    
    Args:
        df (pd.DataFrame): DataFrame containing race data.
        text_block (str): Text block where the first line is a date and the subsequent lines are track names.
    """
    missing = False
    
    # Extract the date from the text block
    formatted_date = extract_date_from_text(text_block)
    if not formatted_date:
        return

    # Extract the track names from the text block (all lines after the date)
    track_names = [line.strip() for line in text_block.strip().splitlines()[1:]]

    # Check if each track name exists in the DataFrame for the corresponding date
    for track in track_names:
        search_pattern = f'{formatted_date}_{track}'
        if not df['race_id'].str.contains(search_pattern, na=False).any():
            print(f"No match found for {search_pattern}")
            missing = True
            
    return missing

def main(file_path, date_track_blocks):
    """
    Main function to load the Excel file, check for duplicates, and verify tracks in the text blocks.
    
    Args:
        file_path (str): Path to the Excel file.
        date_track_blocks (list): List of text blocks, each containing a date and track names.
    """
    # Load the Excel file
    df = load_excel(file_path)
    if df is None:
        return

    any_missing = False
    
    # Check for track name matches based on date and track blocks
    for text_block in date_track_blocks:
        if check_tracks_in_excel(df, text_block):
            any_missing = True
    if not any_missing:
        print("No files missing.")

    # Check for duplicates in the DataFrame
    find_duplicates(df)

if __name__ == "__main__":
    # Define the path to the Excel file
    file_path = 'select_race_data.xlsx'
    
    # Define the list of text blocks with dates and track names (currently empty, to be populated later)
    date_track_blocks = ['''Wednesday, July 1 2020
AJAX DOWNS
ARAPAHOE PARK
ASSINIBOIA DOWNS
BELTERRA PARK
CANTERBURY PARK
DELAWARE PARK
DELTA DOWNS
EMERALD DOWNS
EVANGELINE DOWNS
GRANTS PASS
GULFSTREAM PARK
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PENN NATIONAL
POCATELLO DOWNS
TAMPA BAY DOWNS
THISTLEDOWN''',
'''Thursday, July 2 2020
BELMONT PARK
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
DELTA DOWNS
ELLIS PARK
EMERALD DOWNS
EVANGELINE DOWNS
HOLLYWOOD CASINO AT CHARLES TOWN RACES
HORSESHOE INDIANAPOLIS
LOS ALAMITOS RACE COURSE
THISTLEDOWN
WOODBINE''',
'''Friday, July 3 2020
BELMONT PARK
BELTERRA PARK
CAMARERO RACE TRACK
CENTURY MILE
DELTA DOWNS
ELLIS PARK
EVANGELINE DOWNS
FAIR MEADOWS
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LOS ALAMITOS
LOS ALAMITOS RACE COURSE
MONMOUTH PARK
PENN NATIONAL
PLEASANTON
PRAIRIE MEADOWS
RETAMA PARK
RUIDOSO DOWNS
WOODBINE''',
'''Saturday, July 4 2020
BELMONT PARK
CAMARERO RACE TRACK
DELAWARE PARK
DELTA DOWNS
ELLIS PARK
EVANGELINE DOWNS
FAIR MEADOWS
GILLESPIE COUNTY FAIRGROUND
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
HORSESHOE INDIANAPOLIS
LAUREL PARK
LOS ALAMITOS RACE COURSE
LOUISIANA DOWNS
MONMOUTH PARK
PLEASANTON
PRAIRIE MEADOWS
RETAMA PARK
RUIDOSO DOWNS
THISTLEDOWN
WOODBINE
WYOMING DOWNS''',
'''Sunday, July 5 2020
BELMONT PARK
CAMARERO RACE TRACK
CENTURY MILE
ELLIS PARK
GILLESPIE COUNTY FAIRGROUND
GULFSTREAM PARK
LONE STAR PARK
LOS ALAMITOS
LOS ALAMITOS RACE COURSE
MONMOUTH PARK
MOUNTAINEER CASINO RACETRACK & RESORT
PLEASANTON
PRAIRIE MEADOWS
RUIDOSO DOWNS
WOODBINE
WYOMING DOWNS''',
'''Monday, July 6 2020
ARAPAHOE PARK
ASSINIBOIA DOWNS
CANTERBURY PARK
DELAWARE PARK
FAIR MEADOWS
FAIRMOUNT PARK
FORT ERIE
GRANTS PASS
HASTINGS RACECOURSE
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRAIRIE MEADOWS
THISTLEDOWN''',
'''Tuesday, July 7 2020
ARAPAHOE PARK
ASSINIBOIA DOWNS
BELTERRA PARK
CANTERBURY PARK
FAIR MEADOWS
FAIRMOUNT PARK
FORT ERIE
GRANTS PASS
HASTINGS RACECOURSE
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
THISTLEDOWN''',
'''Wednesday, July 8 2020
AJAX DOWNS
ARAPAHOE PARK
ASSINIBOIA DOWNS
BELTERRA PARK
CANTERBURY PARK
DELAWARE PARK
DELTA DOWNS
EMERALD DOWNS
EVANGELINE DOWNS
GRANTS PASS
GULFSTREAM PARK
HORSESHOE INDIANAPOLIS
KEENELAND
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PENN NATIONAL
POCATELLO DOWNS
THISTLEDOWN''',
'''Thursday, July 9 2020
BELMONT PARK
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
DELTA DOWNS
EMERALD DOWNS
EVANGELINE DOWNS
HOLLYWOOD CASINO AT CHARLES TOWN RACES
HORSESHOE INDIANAPOLIS
KEENELAND
RETAMA PARK
THISTLEDOWN
WOODBINE''',
'''Friday, July 10 2020
BELMONT PARK
BELTERRA PARK
CAMARERO RACE TRACK
CENTURY MILE
DEL MAR
DELTA DOWNS
EVANGELINE DOWNS
FAIR MEADOWS
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
KEENELAND
LAUREL PARK
LOS ALAMITOS
MONMOUTH PARK
PENN NATIONAL
PLEASANTON
PRAIRIE MEADOWS
RETAMA PARK
RUIDOSO DOWNS
WOODBINE''',
'''Saturday, July 11 2020
BELMONT PARK
CAMARERO RACE TRACK
DEL MAR
DELAWARE PARK
DELTA DOWNS
EVANGELINE DOWNS
FAIR MEADOWS
GRANDE PRAIRIE
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
KEENELAND
LAUREL PARK
LOS ALAMITOS
LOUISIANA DOWNS
MONMOUTH PARK
PLEASANTON
PRAIRIE MEADOWS
RETAMA PARK
RUIDOSO DOWNS
WOODBINE
WYOMING DOWNS''',
'''Sunday, July 12 2020
BELMONT PARK
CAMARERO RACE TRACK
CENTURY MILE
DEL MAR
FAIR MEADOWS
GRANDE PRAIRIE
GULFSTREAM PARK
KEENELAND
LONE STAR PARK
LOS ALAMITOS
MONMOUTH PARK
MOUNTAINEER CASINO RACETRACK & RESORT
PLEASANTON
PRAIRIE MEADOWS
RUIDOSO DOWNS
WOODBINE
WYOMING DOWNS''',
'''Monday, July 13 2020
ARAPAHOE PARK
ASSINIBOIA DOWNS
CANTERBURY PARK
DELAWARE PARK
FAIR MEADOWS
FAIRMOUNT PARK
FORT ERIE
HASTINGS RACECOURSE
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRAIRIE MEADOWS
THISTLEDOWN''',
'''Tuesday, July 14 2020
ARAPAHOE PARK
ASSINIBOIA DOWNS
BELTERRA PARK
CANTERBURY PARK
FAIR MEADOWS
FAIRMOUNT PARK
FORT ERIE
HASTINGS RACECOURSE
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
THISTLEDOWN''',
'''Wednesday, July 15 2020
AJAX DOWNS
ARAPAHOE PARK
ASSINIBOIA DOWNS
BELTERRA PARK
CANTERBURY PARK
DELAWARE PARK
DELTA DOWNS
EMERALD DOWNS
EVANGELINE DOWNS
GULFSTREAM PARK
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PENN NATIONAL
POCATELLO DOWNS
THISTLEDOWN''',
'''Thursday, July 16 2020
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
DELAWARE PARK
DELTA DOWNS
EMERALD DOWNS
EVANGELINE DOWNS
HOLLYWOOD CASINO AT CHARLES TOWN RACES
HORSESHOE INDIANAPOLIS
RETAMA PARK
SARATOGA
THISTLEDOWN
WOODBINE''',
'''Friday, July 17 2020
BELTERRA PARK
CAMARERO RACE TRACK
CENTURY MILE
DEL MAR
DELTA DOWNS
ELLIS PARK
EVANGELINE DOWNS
FAIR MEADOWS
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LOS ALAMITOS
MONMOUTH PARK
NORTH DAKOTA HORSE PARK
PENN NATIONAL
PLEASANTON
POCATELLO DOWNS
PRAIRIE MEADOWS
RETAMA PARK
RUIDOSO DOWNS
SARATOGA
WOODBINE''',
'''Saturday, July 18 2020
CAMARERO RACE TRACK
DEL MAR
DELAWARE PARK
DELTA DOWNS
ELLIS PARK
EVANGELINE DOWNS
FAIR MEADOWS
GILLESPIE COUNTY FAIRGROUND
GRANDE PRAIRIE
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LOS ALAMITOS
LOUISIANA DOWNS
MONMOUTH PARK
NORTH DAKOTA HORSE PARK
PLEASANTON
PRAIRIE MEADOWS
RETAMA PARK
RUIDOSO DOWNS
SARATOGA
WOODBINE
WYOMING DOWNS''',
'''Sunday, July 19 2020
ARAPAHOE PARK
CAMARERO RACE TRACK
CENTURY MILE
ELLIS PARK
FAIR MEADOWS
GILLESPIE COUNTY FAIRGROUND
GRANDE PRAIRIE
GULFSTREAM PARK
LONE STAR PARK
LOS ALAMITOS
MONMOUTH PARK
MOUNTAINEER CASINO RACETRACK & RESORT
PLEASANTON
PRAIRIE MEADOWS
RUIDOSO DOWNS
SARATOGA
WOODBINE
WYOMING DOWNS''',
'''Monday, July 20 2020
ARAPAHOE PARK
ASSINIBOIA DOWNS
CANTERBURY PARK
DELAWARE PARK
FAIR MEADOWS
FAIRMOUNT PARK
FINGER LAKES
FORT ERIE
HASTINGS RACECOURSE
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRAIRIE MEADOWS
THISTLEDOWN''',
'''Tuesday, July 21 2020
ARAPAHOE PARK
ASSINIBOIA DOWNS
BELTERRA PARK
CANTERBURY PARK
FAIR MEADOWS
FAIRMOUNT PARK
FINGER LAKES
FORT ERIE
HASTINGS RACECOURSE
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
THISTLEDOWN''',
'''Wednesday, July 22 2020
AJAX DOWNS
ARAPAHOE PARK
ASSINIBOIA DOWNS
BELTERRA PARK
CANTERBURY PARK
DELAWARE PARK
EMERALD DOWNS
EVANGELINE DOWNS
FINGER LAKES
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PENN NATIONAL
SARATOGA
THISTLEDOWN''',
'''Thursday, July 23 2020
ARLINGTON
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
DELAWARE PARK
DELTA DOWNS
EMERALD DOWNS
EVANGELINE DOWNS
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
HORSESHOE INDIANAPOLIS
LAUREL PARK
RETAMA PARK
SARATOGA
THISTLEDOWN
WOODBINE''',
'''Friday, July 24 2020
ARLINGTON
BELTERRA PARK
CAMARERO RACE TRACK
CENTURY MILE
DEL MAR
DELTA DOWNS
ELLIS PARK
EVANGELINE DOWNS
FAIR MEADOWS
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LOS ALAMITOS
MONMOUTH PARK
PENN NATIONAL
PLEASANTON
PRAIRIE MEADOWS
RETAMA PARK
RUIDOSO DOWNS
SARATOGA
WOODBINE''',
'''Saturday, July 25 2020
ARLINGTON
CAMARERO RACE TRACK
DEL MAR
DELAWARE PARK
DELTA DOWNS
ELLIS PARK
EVANGELINE DOWNS
FAIR MEADOWS
GRANDE PRAIRIE
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LOS ALAMITOS
LOUISIANA DOWNS
MONMOUTH PARK
NORTH DAKOTA HORSE PARK
PLEASANTON
PRAIRIE MEADOWS
RETAMA PARK
RUIDOSO DOWNS
SARATOGA
WOODBINE
WYOMING DOWNS''',
'''Sunday, July 26 2020
CENTURY MILE
DEL MAR
ELLIS PARK
FAIR MEADOWS
GRANDE PRAIRIE
GULFSTREAM PARK
LONE STAR PARK
LOS ALAMITOS
MONMOUTH PARK
MOUNTAINEER CASINO RACETRACK & RESORT
NORTH DAKOTA HORSE PARK
PLEASANTON
PRAIRIE MEADOWS
RUIDOSO DOWNS
SARATOGA
WOODBINE
WYOMING DOWNS''',
'''Monday, July 27 2020
ARAPAHOE PARK
ASSINIBOIA DOWNS
CAMARERO RACE TRACK
CANTERBURY PARK
COLONIAL DOWNS
DEL MAR
DELAWARE PARK
FAIRMOUNT PARK
FINGER LAKES
FORT ERIE
HASTINGS RACECOURSE
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRAIRIE MEADOWS
PRESQUE ISLE DOWNS
THISTLEDOWN''',
'''Tuesday, July 28 2020
ARAPAHOE PARK
ASSINIBOIA DOWNS
BELTERRA PARK
CANTERBURY PARK
COLONIAL DOWNS
FAIRMOUNT PARK
FINGER LAKES
FORT ERIE
HASTINGS RACECOURSE
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
THISTLEDOWN''',
'''Wednesday, July 29 2020
AJAX DOWNS
ARAPAHOE PARK
ASSINIBOIA DOWNS
BELTERRA PARK
CANTERBURY PARK
COLONIAL DOWNS
DELAWARE PARK
EMERALD DOWNS
EVANGELINE DOWNS
FINGER LAKES
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PENN NATIONAL
PRESQUE ISLE DOWNS
SARATOGA
THISTLEDOWN''',
'''Thursday, July 30 2020
ARLINGTON
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
DELAWARE PARK
DELTA DOWNS
EMERALD DOWNS
EVANGELINE DOWNS
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
HORSESHOE INDIANAPOLIS
LAUREL PARK
RETAMA PARK
SARATOGA
THISTLEDOWN
WOODBINE''',
'''Friday, July 31 2020
ARLINGTON
BELTERRA PARK
CAMARERO RACE TRACK
CENTURY MILE
DEL MAR
DELTA DOWNS
ELLIS PARK
EVANGELINE DOWNS
GOLDEN GATE FIELDS
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LOS ALAMITOS
MONMOUTH PARK
PENN NATIONAL
POCATELLO DOWNS
PRAIRIE MEADOWS
RETAMA PARK
RUIDOSO DOWNS
SARATOGA
WOODBINE''']

    # Run the main function
    main(file_path, date_track_blocks)
