import os
import pandas as pd
import re

# Set the working directory to the script's location
script_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(script_dir)

def load_excel(file_path):
    """
    Loads the Excel file into a pandas DataFrame.
    
    Args:
        file_path (str): The path to the Excel file.

    Returns:
        pd.DataFrame: DataFrame containing the contents of the Excel file.
    """
    try:
        df = pd.read_excel(file_path)
        return df
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return None

def find_duplicates(df):
    """
    Finds and prints duplicate entries in the DataFrame based on 'race_id' and 'horse_name'.
    
    Args:
        df (pd.DataFrame): DataFrame containing race data.
    """
    # Identify duplicates based on race_id and horse_name
    duplicates = df[df.duplicated(subset=['race_id', 'horse_name'], keep=False)]
    
    if not duplicates.empty:
        # If duplicates exist, print the file number, race ID, and horse name for the duplicates
        print("Duplicate entries found:")
        duplicate_pairs = duplicates[['file_number', 'race_id', 'horse_name']]
        print(duplicate_pairs)
    else:
        print("No duplicates found.")

def extract_date_from_text(text_block):
    """
    Extracts the date from the first line of the given text block.
    
    Args:
        text_block (str): Text block where the first line contains the date.

    Returns:
        str: Formatted date in 'Month Day, Year' format if successful, otherwise None.
    """
    lines = text_block.strip().splitlines()
    date_line = lines[0].strip()  # First line is assumed to be the date
    date_pattern = r'(\w+), (\w+) (\d{1,2}) (\d{4})'
    
    # Match the date pattern
    match = re.match(date_pattern, date_line)
    if match:
        day_name, month, day, year = match.groups()
        return f'{month} {day}, {year}'
    else:
        print("Invalid date format in the text block.")
        return None

def check_tracks_in_excel(df, text_block):
    """
    Checks if each track name from the text block is present in the DataFrame for the corresponding date.
    
    Args:
        df (pd.DataFrame): DataFrame containing race data.
        text_block (str): Text block where the first line is a date and the subsequent lines are track names.
    """
    missing = False
    
    # Extract the date from the text block
    formatted_date = extract_date_from_text(text_block)
    if not formatted_date:
        return

    # Extract the track names from the text block (all lines after the date)
    track_names = [line.strip() for line in text_block.strip().splitlines()[1:]]

    # Check if each track name exists in the DataFrame for the corresponding date
    for track in track_names:
        search_pattern = f'{formatted_date}_{track}'
        if not df['race_id'].str.contains(search_pattern, na=False).any():
            print(f"No match found for {search_pattern}")
            missing = True
            
    return missing

def main(file_path, date_track_blocks):
    """
    Main function to load the Excel file, check for duplicates, and verify tracks in the text blocks.
    
    Args:
        file_path (str): Path to the Excel file.
        date_track_blocks (list): List of text blocks, each containing a date and track names.
    """
    # Load the Excel file
    df = load_excel(file_path)
    if df is None:
        return

    any_missing = False
    
    # Check for track name matches based on date and track blocks
    for text_block in date_track_blocks:
        if check_tracks_in_excel(df, text_block):
            any_missing = True
    if not any_missing:
        print("No files missing.")

    # Check for duplicates in the DataFrame
    find_duplicates(df)

if __name__ == "__main__":
    # Define the path to the Excel file
    file_path = 'select_race_data.xlsx'
    
    # Define the list of text blocks with dates and track names (currently empty, to be populated later)
    date_track_blocks = ['''Sunday, September 1 2024
AJAX DOWNS
ALBUQUERQUE
BLACKFOOT
CAMARERO RACE TRACK
CANTERBURY PARK
DEL MAR
ELKO COUNTY FAIR
EMERALD DOWNS
FERNDALE
GULFSTREAM PARK
HARRAH'S COLUMBUS NEBRASKA
HAWTHORNE
KENTUCKY DOWNS
LETHBRIDGE - RMTC
LOS ALAMITOS
MONMOUTH PARK
MOUNTAINEER CASINO RACETRACK & RESORT
PRAIRIE MEADOWS
SARATOGA
SWEETWATER DOWNS
TIMONIUM
WOODBINE''',
'''Monday, September 2 2024
ALBUQUERQUE
ASSINIBOIA DOWNS
BLACKFOOT
CAMARERO RACE TRACK
CANTERBURY PARK
DEL MAR
ELKO COUNTY FAIR
FERNDALE
FINGER LAKES
FORT ERIE
HARRAH'S COLUMBUS NEBRASKA
LETHBRIDGE - RMTC
LOUISIANA DOWNS
MONMOUTH PARK
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRAIRIE MEADOWS
PRESQUE ISLE DOWNS
SARATOGA
THISTLEDOWN
TIMONIUM
WOODBINE''',
'''Tuesday, September 3 2024
ASSINIBOIA DOWNS
FINGER LAKES
FORT ERIE
FanDuel Sportsbook and Horse Racing
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
THISTLEDOWN''',
'''Wednesday, September 4 2024
ASSINIBOIA DOWNS
BELTERRA PARK
COLONIAL DOWNS
DELAWARE PARK
FINGER LAKES
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
REMINGTON PARK
THISTLEDOWN''',
'''Thursday, September 5 2024
ALBUQUERQUE
BELTERRA PARK
CANTERBURY PARK
COLONIAL DOWNS
DEL MAR
DELAWARE PARK
FAIR GROUNDS
HAWTHORNE
HORSESHOE INDIANAPOLIS
KENTUCKY DOWNS
REMINGTON PARK
THISTLEDOWN
WOODBINE''',
'''Friday, September 6 2024
ALBUQUERQUE
ARAPAHOE PARK
BELTERRA PARK
BLACKFOOT
CAMARERO RACE TRACK
CENTURY MILE
COLONIAL DOWNS
DEL MAR
EMERALD DOWNS
FAIR GROUNDS
GULFSTREAM PARK
HARRAH'S COLUMBUS NEBRASKA
HASTINGS RACECOURSE
HORSESHOE INDIANAPOLIS
LONE STAR PARK
PRAIRIE MEADOWS
REMINGTON PARK
SWEETWATER DOWNS
WOODBINE''',
'''Saturday, September 7 2024
ALBUQUERQUE
ARAPAHOE PARK
BELTERRA PARK
BLACKFOOT
CAMARERO RACE TRACK
CANTERBURY PARK
CENTURY MILE
COLONIAL DOWNS
DEL MAR
DELAWARE PARK
EMERALD DOWNS
FAIR GROUNDS
FERNDALE
FanDuel Sportsbook and Horse Racing
GULFSTREAM PARK
HARRAH'S COLUMBUS NEBRASKA
HASTINGS RACECOURSE
KENTUCKY DOWNS
LAUREL PARK
LETHBRIDGE - RMTC
LONE STAR PARK
LOS ALAMITOS
MONMOUTH PARK
PRAIRIE MEADOWS
REMINGTON PARK
SWEETWATER DOWNS
WOODBINE''',
'''Sunday, September 8 2024
ALBUQUERQUE
ARAPAHOE PARK
CAMARERO RACE TRACK
DEL MAR
EMERALD DOWNS
FERNDALE
GRANTS PASS
GULFSTREAM PARK
HARRAH'S COLUMBUS NEBRASKA
HAWTHORNE
KENTUCKY DOWNS
LAUREL PARK
LETHBRIDGE - RMTC
LOS ALAMITOS
MONMOUTH PARK
MOUNTAINEER CASINO RACETRACK & RESORT
PRAIRIE MEADOWS
SWEETWATER DOWNS
WOODBINE''',
'''Monday, September 9 2024
ASSINIBOIA DOWNS
FINGER LAKES
FORT ERIE
GRANTS PASS
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRAIRIE MEADOWS
PRESQUE ISLE DOWNS
THISTLEDOWN
WILL ROGERS DOWNS''',
'''Tuesday, September 10 2024
ASSINIBOIA DOWNS
FINGER LAKES
FORT ERIE
FanDuel Sportsbook and Horse Racing
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
THISTLEDOWN
WILL ROGERS DOWNS''',
'''Wednesday, September 11 2024
AJAX DOWNS
ALBUQUERQUE
ASSINIBOIA DOWNS
BELTERRA PARK
DELAWARE PARK
FINGER LAKES
HORSESHOE INDIANAPOLIS
KENTUCKY DOWNS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
REMINGTON PARK
THISTLEDOWN''',
'''Thursday, September 12 2024
ALBUQUERQUE
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
CHURCHILL DOWNS
DELAWARE PARK
FAIR GROUNDS
HAWTHORNE
HOLLYWOOD CASINO AT CHARLES TOWN RACES
HORSESHOE INDIANAPOLIS
LONE STAR PARK
REMINGTON PARK
THISTLEDOWN
WOODBINE''',
'''Friday, September 13 2024
ALBUQUERQUE
ARAPAHOE PARK
BELMONT AT THE BIG A
BELTERRA PARK
CAMARERO RACE TRACK
CENTURY MILE
CHURCHILL DOWNS
DELAWARE PARK
EMERALD DOWNS
FAIR GROUNDS
FRESNO
GULFSTREAM PARK
HARRAH'S COLUMBUS NEBRASKA
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LONE STAR PARK
LOS ALAMITOS RACE COURSE
PRAIRIE MEADOWS
REMINGTON PARK
SWEETWATER DOWNS
WOODBINE''',
'''Saturday, September 14 2024
ALBUQUERQUE
ARAPAHOE PARK
BELMONT AT THE BIG A
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
CENTURY MILE
CHURCHILL DOWNS
DELAWARE PARK
EMERALD DOWNS
FAIR GROUNDS
FRESNO
FanDuel Sportsbook and Horse Racing
GULFSTREAM PARK
HARRAH'S COLUMBUS NEBRASKA
HASTINGS RACECOURSE
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LETHBRIDGE - RMTC
LONE STAR PARK
LOS ALAMITOS
LOS ALAMITOS RACE COURSE
LOUISIANA DOWNS
MONMOUTH PARK
PRAIRIE MEADOWS
REMINGTON PARK
SWEETWATER DOWNS
WOODBINE''',
'''Sunday, September 15 2024
ALBUQUERQUE
ARAPAHOE PARK
BELMONT AT THE BIG A
CAMARERO RACE TRACK
CHURCHILL DOWNS
EMERALD DOWNS
FAIR GROUNDS
FRESNO
GRANTS PASS
GULFSTREAM PARK
HARRAH'S COLUMBUS NEBRASKA
HASTINGS RACECOURSE
HAWTHORNE
LAUREL PARK
LETHBRIDGE - RMTC
LOS ALAMITOS
LOS ALAMITOS RACE COURSE
MONMOUTH PARK
MOUNTAINEER CASINO RACETRACK & RESORT
PRAIRIE MEADOWS
SWEETWATER DOWNS
WOODBINE''',
'''Monday, September 16 2024
ASSINIBOIA DOWNS
FINGER LAKES
FORT ERIE
GRANTS PASS
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRAIRIE MEADOWS
PRESQUE ISLE DOWNS
THISTLEDOWN
WILL ROGERS DOWNS''',
'''Tuesday, September 17 2024
ASSINIBOIA DOWNS
FINGER LAKES
FORT ERIE
FanDuel Sportsbook and Horse Racing
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
THISTLEDOWN
WILL ROGERS DOWNS''',
'''Wednesday, September 18 2024
AJAX DOWNS
ALBUQUERQUE
ASSINIBOIA DOWNS
BELTERRA PARK
CHURCHILL DOWNS
DELAWARE PARK
FINGER LAKES
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
REMINGTON PARK
THISTLEDOWN''',
'''Thursday, September 19 2024
ALBUQUERQUE
BELMONT AT THE BIG A
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
CHURCHILL DOWNS
DELAWARE PARK
HAWTHORNE
HOLLYWOOD CASINO AT CHARLES TOWN RACES
HORSESHOE INDIANAPOLIS
LONE STAR PARK
REMINGTON PARK
THISTLEDOWN
WOODBINE''',
'''Friday, September 20 2024
ALBUQUERQUE
ARAPAHOE PARK
BELMONT AT THE BIG A
BELTERRA PARK
CAMARERO RACE TRACK
CHURCHILL DOWNS
DELAWARE PARK
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LEGACY DOWNS
LONE STAR PARK
LOS ALAMITOS RACE COURSE
MEADOWLANDS
PRAIRIE MEADOWS
PRESQUE ISLE DOWNS
REMINGTON PARK
WOODBINE''',
'''Saturday, September 21 2024
ALBUQUERQUE
ARAPAHOE PARK
BELMONT AT THE BIG A
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
CENTURY DOWNS
CHURCHILL DOWNS
DELAWARE PARK
FRESNO
FanDuel Sportsbook and Horse Racing
GULFSTREAM PARK
HASTINGS RACECOURSE
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LEGACY DOWNS
LETHBRIDGE - RMTC
LONE STAR PARK
LOS ALAMITOS
LOS ALAMITOS RACE COURSE
MEADOWLANDS
PARX RACING
PRAIRIE MEADOWS
REMINGTON PARK
SWEETWATER DOWNS
WOODBINE''',
'''Sunday, September 22 2024
ALBUQUERQUE
ARAPAHOE PARK
BELMONT AT THE BIG A
CAMARERO RACE TRACK
CENTURY DOWNS
CHURCHILL DOWNS
FRESNO
GRANTS PASS
GULFSTREAM PARK
HASTINGS RACECOURSE
HAWTHORNE
LAUREL PARK
LETHBRIDGE - RMTC
LOS ALAMITOS
LOS ALAMITOS RACE COURSE
MOUNTAINEER CASINO RACETRACK & RESORT
PRAIRIE MEADOWS
SWEETWATER DOWNS
WILL ROGERS DOWNS
WOODBINE''',
'''Monday, September 23 2024
ASSINIBOIA DOWNS
FINGER LAKES
FORT ERIE
GRANTS PASS
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRAIRIE MEADOWS
PRESQUE ISLE DOWNS
THISTLEDOWN
WILL ROGERS DOWNS''',
'''Tuesday, September 24 2024
ASSINIBOIA DOWNS
FINGER LAKES
FORT ERIE
FanDuel Sportsbook and Horse Racing
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
THISTLEDOWN
WILL ROGERS DOWNS''',
'''Wednesday, September 25 2024
AJAX DOWNS
ALBUQUERQUE
BELTERRA PARK
CANTERBURY PARK
CHURCHILL DOWNS
DELAWARE PARK
FINGER LAKES
HORSESHOE INDIANAPOLIS
LOUISIANA DOWNS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
THISTLEDOWN''',
'''Thursday, September 26 2024
ALBUQUERQUE
BELMONT AT THE BIG A
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
CHURCHILL DOWNS
DELAWARE PARK
HAWTHORNE
HOLLYWOOD CASINO AT CHARLES TOWN RACES
HORSESHOE INDIANAPOLIS
LONE STAR PARK
LOUISIANA DOWNS
PRAIRIE MEADOWS
PRESQUE ISLE DOWNS
REMINGTON PARK
THISTLEDOWN
WOODBINE''',
'''Friday, September 27 2024
ALBUQUERQUE
ARAPAHOE PARK
BELMONT AT THE BIG A
BELTERRA PARK
CAMARERO RACE TRACK
CHURCHILL DOWNS
DELAWARE PARK
GULFSTREAM PARK
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LEGACY DOWNS
LONE STAR PARK
MEADOWLANDS
PRAIRIE MEADOWS
REMINGTON PARK
SANTA ANITA PARK
WOODBINE''',
'''Saturday, September 28 2024
ALBUQUERQUE
ARAPAHOE PARK
BELMONT AT THE BIG A
BELTERRA PARK
CAMARERO RACE TRACK
CANTERBURY PARK
CENTURY DOWNS
CHURCHILL DOWNS
DELAWARE PARK
FRESNO
FanDuel Sportsbook and Horse Racing
GULFSTREAM PARK
HASTINGS RACECOURSE
HOLLYWOOD CASINO AT CHARLES TOWN RACES
LAUREL PARK
LEGACY DOWNS
LETHBRIDGE - RMTC
LONE STAR PARK
LOS ALAMITOS
MEADOWLANDS
PRAIRIE MEADOWS
REMINGTON PARK
SANTA ANITA PARK
SHAWAN DOWNS
SWEETWATER DOWNS
WOODBINE''',
'''Sunday, September 29 2024
ALBUQUERQUE
ARAPAHOE PARK
BELMONT AT THE BIG A
CAMARERO RACE TRACK
CENTURY DOWNS
CHURCHILL DOWNS
FRESNO
GRANTS PASS
GULFSTREAM PARK
HASTINGS RACECOURSE
HAWTHORNE
HORSEMEN'S PARK
LAUREL PARK
LETHBRIDGE - RMTC
LOS ALAMITOS
MOUNTAINEER CASINO RACETRACK & RESORT
REMINGTON PARK
SANTA ANITA PARK
SWEETWATER DOWNS
WILL ROGERS DOWNS
WOODBINE''',
'''Monday, September 30 2024
FINGER LAKES
FORT ERIE
GRANTS PASS
HORSESHOE INDIANAPOLIS
MOUNTAINEER CASINO RACETRACK & RESORT
PARX RACING
PRESQUE ISLE DOWNS
THISTLEDOWN
WILL ROGERS DOWNS''']

    # Run the main function
    main(file_path, date_track_blocks)
